#!/bin/bash

ARCH=$(uname -m)
if [ $ARCH == 'x86_64' ]; then
    curl -O https://amazon-ssm-us-east-1.s3.amazonaws.com/latest/debian_amd64/amazon-ssm-agent.deb -o /tmp/amazon-ssm-agent.deb
else
    curl -O https://amazon-ssm-us-east-1.s3.amazonaws.com/latest/debian_amd64/amazon-ssm-agent.deb -o /tmp/amazon-ssm-agent.deb
fi
    sudo dpkg -i /tmp/amazon-ssm-agent.deb
    sudo status amazon-ssm-agent
    sudo start amazon-ssm-agent
    sudo status amazon-ssm-agent
